import './globals.css'
import './styles.css'

export const metadata = {
  title: 'Quillami',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="antialiased">{children}</body>
    </html>
  )
}
